### ISSUE TITLE
Model refactoring with TaskGraph and user-facing changes

### ISSUE THREAD

**Issue by phargogh** [natcap/invest.users-guide#1]
As TaskGraph functionality is added to an InVEST model, there are usually some small user-facing changes. Typically these include the new n_workers argument in the UI, and some new/different file structure in the output workspace. Temp files that a model formerly removed at the end of execution will often now persist so that taskgraph can find them and avoid re-calculation.

So, here's an issue to remind me to edit the user's guide for these models sometime right before/after our next InVEST release. The most important thing is probably to keep the "Model Outputs" sections current.

**Originally reported by @davemfish at https://bitbucket.org/natcap/invest.users-guide/issues/5/model-refactoring-with-taskgraph-and-user**

**Comment by emlys** [comment]
I think this has mostly been addressed... I think most models mention the n_workers argument. The "interpreting results" sections aren't perfect, but many have been reviewed since this issue was made. A comprehensive review may happen as part of https://github.com/natcap/invest/issues/596.
