### ISSUE TITLE
RTD build failing on GDAL

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest.users-guide#100]
The RTD build has been failing for awhile now and Lisa noted that when Googling "InVEST Users Guide" the RTD version is the one that comes up first! So it would be nice to better maintain this.

https://readthedocs.org/projects/invest-userguide/builds/18541754/

```python
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> GDAL
```

**Comment by emlys** [comment]
We've stopped building with ReadTheDocs and instead we're uploading dev builds of the user guide to the dev builds bucket where they can be viewed.
