### ISSUE TITLE
Update the website links for InVEST 3.13.0 changes

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest.users-guide#112]
We'll be deprecating the Qt UI versions of InVEST and adding some new links for the translated UGs. We'll want to archive / move the current Chinese and Spanish UG links since they're old and tied to a much older InVEST version.

**Comment by dcdenu4** [comment]
The repository for these changes is here: https://github.com/natcap/invest-download-links

**Comment by phargogh** [comment]
This has been resolved as of https://github.com/natcap/invest-download-links/pull/10
