### ISSUE TITLE
Deprecate globio rst

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest.users-guide#113]
The GLOBIO model was deprecated from InVEST https://github.com/natcap/invest/pull/1138. We should also remove it from the UG.

- [ ] Remove from index.rst
- [ ] Remove globio.rst
- [ ] Remove translated files?

**Comment by phargogh** [comment]
Globio has already been deprecated in the 3.13.0 release, so I think we're already good to go on this.  I'll close the issue, please feel free to reopen if needed!
