### ISSUE TITLE
SWY quickflow update

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest.users-guide#128]
Emily did some recent work that was merged in https://github.com/natcap/invest/pull/1109. I can't remember if there was a Users Guide update component to that work, or it'd be worth noting any assumptions we end up making or constraints we end up implementing.

@emlys , what do you think?

**Comment by emlys** [comment]
Done in https://github.com/natcap/invest.users-guide/commit/3126846e51990d9a3b6520f7c8481709aeb27fb4!
