### ISSUE TITLE
Update allowed CSV delimiters

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest.users-guide#130]
There are a few places in the UG where we say that it is required for CSV table inputs to be comma separated. InVEST actually lets the pandas library handle delimiters and we don't have a tight contract they need to be commas. Semicolons work just fine too for example.

So, update the UG to reflect this.

InVEST issue https://github.com/natcap/invest/issues/1296 mentions mentions the `getting_started` page has something that would need updating.

**Comment by emlys** [comment]
Done in https://github.com/natcap/invest.users-guide/commit/a9abc3efbb5eac5ba53772f6a30e3af0dcfc9939
