### ISSUE TITLE
The title bar is not showing an invest version

### ISSUE THREAD

**Issue by davemfish** [natcap/invest.users-guide#17]
![UG](https://user-images.githubusercontent.com/4071255/107042676-de669a00-6776-11eb-939e-13b42de83dcd.PNG)

I think we used to have an invest version string up there on the top bar, right?

**Comment by phargogh** [comment]
We sure did, even as of [3.9.0](https://storage.googleapis.com/releases.naturalcapitalproject.org/invest/3.9.0/userguide/index.html)!  Maybe it's excluded for dev builds?

**Comment by davemfish** [comment]
Oh weird. Now I see that it's there also for dev builds, it's just not there for the version filed under `/latest`

https://storage.googleapis.com/releases.naturalcapitalproject.org/invest-userguide/latest/index.html

**Comment by davemfish** [comment]
> it's just not there for the version filed under `invest-userguide/latest`

Maybe that makes sense because that UG is probably being built from the `natcap/invest.users-guide` build process, while the others with version strings are being built within the `invest` build process. So maybe this isn't a bug at all!
