### ISSUE TITLE
Copyright year should be programmatically derived from the current commit

### ISSUE THREAD

**Issue by phargogh** [natcap/invest.users-guide#3]
In the User's Guide, we need to remember to update the year each year, which leads to the year itself being out of date.  Instead, it would be preferable if we could derive the year from the latest commit rather than remembering to do this ourselves.

**Comment by phargogh** [comment]
My thinking about this issue originally was that it seemed like the copyright year should be associated with the date of latest edit to the repo rather than the date the UG was built.

But after talking with @emlys about this a little, it sounds like the correct copyright year to use might actually be either the original year of release or a range of years (e.g. 2008-2022).

In either case, I've added this to the list of things I'd like to ask Stanford's General Counsel and so I'll post back here when I find out.

**Comment by phargogh** [comment]
Our contact at OTL responded with:

> 2)	The inclusion of a copyright notice is not a requirement.  Likewise the inclusion of some date indication, eg, “Year” is not a requirement.  So, you can put the current version’s year, a range of years, or no year.  Check out the Stanford homepage – it uses: ©Copyright Stanford University.   Stanford, California 94305. 

So I think we can use whatever we want, or not have a year at all ... I'm reading this as it doesn't matter.  What do you think?

**Comment by emlys** [comment]
Probably easiest to leave the year out, then we don't have to wonder about it again.

**Comment by emlys** [comment]
I removed the year (b377061).
