### ISSUE TITLE
Translations: Add translation infrastructure

### ISSUE THREAD

**Issue by emlys** [natcap/invest.users-guide#33]
- Directories to hold translation files
- call `pybabel compile` as part of the install/build process (converts human-readable .po files to binary .mo files, which are used to look up strings at runtime)
- ?

**Comment by phargogh** [comment]
I believe the sphinx project has some helper utilities for extracting text from RST that may prove helpful: https://www.sphinx-doc.org/en/master/usage/advanced/intl.html

**Comment by emlys** [comment]
This was done in #50.
