### ISSUE TITLE
Document new mask raster in NDR/SDR

### ISSUE THREAD

**Issue by phargogh** [natcap/invest.users-guide#53]
The mask raster we're producing in https://github.com/natcap/invest/issues/621 would be helpful to include in the SDR page's graphic illustrating the effects of different TFAs.

Currently working on this in my fork on `feature/ndr-sdr-what-drains-to-stream`.

**Comment by phargogh** [comment]
@emlys and I were discussing this a little on the side, and it would be really nice to be able to have a script to automate the creation of this image, probably by running SDR or NDR, stylizing the outputs and using `matplotlib` or something similar to build up the PNG to then display in the UG chapter itself.

Although it might be cool to do so, because this involves running a model twice with different TFAs, this need not be run as part of every build.

**Comment by emlys** [comment]
@phargogh, I'm happy to make the script for that

**Comment by emlys** [comment]
@phargogh, did you have something written up for this already? Just asking because of a related forums question.

**Comment by phargogh** [comment]
I do have a branch by that name, but there aren't any meaningful changes.  I think your matplotlib script in #56 superseded those changes.

**Comment by emlys** [comment]
Cool, I just added mentions of `what_drains_to_stream.tif` to the SDR and NDR pages.
