### ISSUE TITLE
Carbon storage ArgsSpec units

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest.users-guide#65]
Stacie reported on Slack:

>... it looks like the User Guide Data Needs section for Carbon Storage somehow lost the units required for the carbon pool table. They need to be added back, but this is one that looks like it might be best added to the investspec?

**Comment by emlys** [comment]
Changes pushed and appearing in the production UG: https://storage.googleapis.com/releases.naturalcapitalproject.org/invest-userguide/latest/carbonstorage.html#data-needs
