### ISSUE TITLE
Units correction and typo in SDR "Interpreting Results" `ARG_SPECS`

### ISSUE THREAD

**Issue by jagoldstein** [natcap/invest.users-guide#92]
The unit of measure for the SDR intermediate result "[slope.tif](https://storage.googleapis.com/releases.naturalcapitalproject.org/invest-userguide/latest/sdr.html#interpreting-results)" is actually given as a [percent (%), not radians](https://stanford-natcap.slack.com/archives/CECFUU1DW/p1655472761275719?thread_ts=1655425702.319909&cid=CECFUU1DW), but is currently incorrectly documented in the UG's `ARG_SPECS`.
[See the API docs.](https://github.com/natcap/pygeoprocessing/blob/main/src/pygeoprocessing/geoprocessing_core.pyx#L287)

Also, there's a typo in the definition of "slope_threshold.tif": great~~h~~er than

**Comment by emlys** [comment]
The slope factor equation and code use percent slope and radian slope together in the same equation, so that's confusing. Will try to figure out if that's correct.

**Comment by emlys** [comment]
Apparently yes, the USDA handbook uses both kinds of slope in the same equation (page 129 of [this PDF](https://www.ars.usda.gov/ARSUserFiles/64080530/RUSLE/AH_703.pdf). 🤔

**Comment by emlys** [comment]
@jagoldstein let me know if the changes in the commit above sound good.

**Comment by jagoldstein** [comment]
Thanks @emlys! these changes look correct to me
