### ISSUE TITLE
Use a new theme?

### ISSUE THREAD

**Issue by emlys** [natcap/invest.users-guide#94]
I'd love to get input on this from folks who work with the users guide a lot... @newtpatrol @jagoldstein @lmandle and Lori?

The users guide is built with a custom theme, which controls the color scheme, font, layout, etc. Our custom theme has continued to work just fine with no maintenance needed for over 12 years! While that's quite an accomplishment, it may be time to consider switching to a built in theme.

The reason to do this now is because of translation. A small handful of English text lives in our custom theme template (search bar label, 'table of contents', etc.). We'd have to set up translation for that template. More modern themes take advantage of Sphinx's built in translation catalog for these common UI labels.

Other minor factors include:
- While the custom theme continues to work, much of the template logic and image files are totally unused
- From what I can tell, the custom theme doesn't do anything that's not included in a built in theme
- Built in themes are well supported and kept up to date for us
- Some built in themes are mobile friendly
- IMO, the custom theme looks dated. 

A theme gallery is available [here](https://sphinx-themes.org/#themes). Here's a couple examples of what the user's guide could look like in different themes:
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/43770515/199130675-c2da51c8-a884-4cf9-9d6d-342dfe7acdb6.png">
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/43770515/199131498-6dcc8168-86a9-49cb-bc28-bbcd54f44812.png">
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/43770515/199131615-8b32503f-ccb5-4b54-b1e1-969afa664dab.png">

**Comment by newtpatrol** [comment]
The current (custom) theme has never bothered me, but I'm also not at all attached to it, so if it makes a lot of other things easier, I fully support switching to a new (built-in) one. Not sure if you want input at this point about which new theme to use (it looks like the current one is based on ADC), but I'm happy to consider the (many) options more closely as needed.

**Comment by davemfish** [comment]
I do have a complaint about the current theme: the line-spacing is too small and the body of text is too wide. That is, lines of text in a paragraph are very close together and very long (unless I change my whole window width). I think that makes the text harder to read than it needs to be. From the samples, it does look like most themes do much better. Thanks @emlys !

**Comment by jagoldstein** [comment]
Thanks for bringing this up @emlys! I fully support switching to a built in theme, for all the reasons you mentioned and also for the very important point from @davemfish about the UX. My biggest hang up is that the current custom theme looks so dated that it may (at least subconsciously) lead users to think that we've run out of funding, the UG isn't maintained often, and is instead an archaic relic whose URL is likely to soon break for good. A fresh and more modern look would better show that we actively maintain the UG because we're sufficiently funded and operating in the 22nd century.

**Comment by emlys** [comment]
Great, thanks for the input everyone! For now lets try the default [alabaster theme](https://sphinx-themes.org/sample-sites/default-alabaster/) which is very popular and generic. I'll make a separate issue for customizing/branding - maybe a future communications person could help with that.

**Comment by emlys** [comment]
Completed in #95
